context:
  name: libmat
  version: "0.1.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/alvgaona/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: ${{ env.get("ARCHIVE_SHA256") }}

build:
  number: 0
  noarch: generic
  skip:
    - win
  script:
    - mkdir -p $PREFIX/include
    - cp mat.h $PREFIX/include/mat.h

tests:
  - package_contents:
      include:
        - mat.h

about:
  homepage: https://github.com/alvgaona/libmat
  license: Apache-2.0
  license_file: LICENSE
  summary: stb-style single-header linear algebra library in pure C
  repository: https://github.com/alvgaona/libmat
